let GetSampleOptionSets = function () {
  return [
    {
      _attributeType: null,
      attributeDescriptor: {
        Initialized: 2,
        LogicalName: "msp_workload",
        Id: {
          guid: "6283fcd2-c4bf-e811-a841-000d3a30956c",
        },
        EntityLogicalName: "msp_engagementmilestone",
        Type: "picklist",
        DisplayName: "Workload",
        Description: "",
        IsGlobalFilterEnabled: false,
        IsSecured: false,
        IsSortableEnabled: false,
        IsValidForAdvancedFind: true,
        IsValidForCreate: true,
        IsValidForRead: true,
        IsValidForUpdate: true,
        IsRetrievable: false,
        IsCustomAttribute: true,
        ColumnNumber: 52,
        Behavior: null,
        DefaultFormValue: -1,
        DefaultValue: -1,
        ImeMode: null,
        OptionSetId: "7183fcd2-c4bf-e811-a841-000d3a30956c",
        OptionSetName: "msp_engagementmilestone_msp_workload",
        OptionSetType: 0,
        OptionSet: [
          {
            Color: "#0000ff",
            Label: "Advanced Analytics Capabilities",
            Value: 861980040,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Advanced Security Capabilities",
            Value: 861980064,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Advanced Voice Capabilities",
            Value: 861980063,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "AI: Azure Machine Learning",
            Value: 861980091,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "AI: Bots",
            Value: 861980092,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "AI: Cognitive Services",
            Value: 861980012,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "AI: Intelligent Automation/RPA (3rd party)",
            Value: 861980017,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "AI: Knowledge Mining",
            Value: 861980100,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Apps: App Innovation (AKS and Containers)",
            Value: 861980081,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Apps: App Innovation (App Service, Serverless)",
            Value: 861980055,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Apps: App Innovation (OpenShift/ARO)",
            Value: 861980078,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Apps: App Innovation Java (PCF, JBoss, Spring, etc)",
            Value: 861980077,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Apps: App Modernization (Website/Webapp)",
            Value: 861980013,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Apps: Blockchain",
            Value: 861980037,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Apps: DevOps (GitHub, Azure DevOps, other)",
            Value: 861980080,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Apps: Gaming",
            Value: 861980042,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "CDS: Azure IoT Edge",
            Value: 861980009,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "D365: Customer Service",
            Value: 861980018,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "D365: Field Service",
            Value: 861980016,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "D365: Finance and Operations",
            Value: 861980047,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "D365: Marketing",
            Value: 861980059,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "D365: Power BI Pro",
            Value: 861980085,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "D365: PowerApps",
            Value: 861980086,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "D365: Project Service Automation",
            Value: 861980015,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "D365: Retail",
            Value: 861980057,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "D365: Sales",
            Value: 861980048,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "D365: Talent",
            Value: 861980058,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Data Azure:  SQL DW Migration",
            Value: 861980006,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label:
              "Data Azure: Analytics, Modern Data Warehouse (SQL DW, Data Lake)",
            Value: 861980011,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Data Azure: Azure Databricks",
            Value: 861980099,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Data Azure: NoSQL Migration / New Apps (Cosmos DB)",
            Value: 861980070,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label:
              "Data Azure: OSS DB Migration / New Apps (MySQL, PostgreSQL, MariaDB)",
            Value: 861980097,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Data Azure: SQL Migration/Managed Instance",
            Value: 861980008,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Data Azure: SQL VMs (IaaS)",
            Value: 861980071,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "EM: AAD",
            Value: 861980027,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "EM: AIP",
            Value: 861980028,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "EM: ATP",
            Value: 861980090,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "EM: InTune",
            Value: 861980025,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "EM: MCAS",
            Value: 861980089,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Exchange Online",
            Value: 861980031,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label:
              "Infra: Azure Security (Sentinel, Security Center, Firewall)",
            Value: 861980043,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: Azure Stack",
            Value: 861980054,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: Azure VMWare Solutions (CloudSimple)",
            Value: 861980026,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: Azure VMWare Solutions (Virtustream)",
            Value: 861980029,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: Business Continuity, Disaster Recovery",
            Value: 861980002,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: Databox Edge",
            Value: 861980020,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: Enterprise Application Infrastructure",
            Value: 861980004,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: High Performance Compute",
            Value: 861980053,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: Infrastructure Migration",
            Value: 861980000,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: Infrastructure Migration (Linux)",
            Value: 861980105,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: Networking (inc. ExpressRoute)",
            Value: 861980005,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: SAP on Azure",
            Value: 861980051,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: Storage & File Systems (inc.ANF)",
            Value: 861980021,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Infra: Windows Virtual Desktop (WVD)",
            Value: 861980001,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "IoT: 3rd party IoT solutions",
            Value: 861980019,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "IoT: Azure Sphere",
            Value: 861980014,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "IoT: IoT Central",
            Value: 861980069,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "IoT: IoT Digital Twins",
            Value: 861980007,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "IoT: IoT Hub and Accelerators",
            Value: 861980049,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Kaizala",
            Value: 861980087,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "O365 ProPlus",
            Value: 861980033,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "OneDrive for Business",
            Value: 861980039,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Outlook Mobile",
            Value: 861980088,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Project Online",
            Value: 861980036,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "SharePoint Online",
            Value: 861980030,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Skype for Business",
            Value: 861980038,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Surface Catalog",
            Value: 861980068,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Surface Standard",
            Value: 861980067,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Teams",
            Value: 861980062,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Win: Windows 10 Deployment – Existing Device",
            Value: 861980045,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Win: Windows 10 Deployment – New Device",
            Value: 861980044,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Win: Windows 10 Post-Deployment Managed Services",
            Value: 861980065,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Win: Windows Defender ATP",
            Value: 861980066,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Yammer",
            Value: 861980032,
            TransitionData: null,
          },
        ],
        ParentPicklistLogicalName: null,
        ChildPicklistLogicalNames: null,
        RequiredLevel: 2,
        SourceType: 0,
        SourceTypeMask: 0,
        CanBeSecuredForCreate: true,
        CanBeSecuredForRead: true,
        CanBeSecuredForUpdate: true,
      },
      _logicalName: "msp_workload",
      _displayName: "Workload",
      _entityLogicalName: "msp_engagementmilestone",
      _optionSet: null,
      defaultFormValue: -1,
    },
    {
      _attributeType: null,
      attributeDescriptor: {
        Initialized: 2,
        LogicalName: "msp_nonrecurring",
        Id: {
          guid: "65644a9d-7b19-e911-a844-000d3a309adf",
        },
        EntityLogicalName: "msp_engagementmilestone",
        Type: "picklist",
        DisplayName: "Non-Recurring?",
        Description:
          "ACR or active users from Non-Recurring Milestones. Unlike regular Milestones, these Milestones reflect a one-time increase/decrease in consumption. \nhttp://aka.ms/NonRecurringMilestones",
        IsGlobalFilterEnabled: false,
        IsSecured: false,
        IsSortableEnabled: false,
        IsValidForAdvancedFind: true,
        IsValidForCreate: true,
        IsValidForRead: true,
        IsValidForUpdate: true,
        IsRetrievable: false,
        IsCustomAttribute: true,
        ColumnNumber: 58,
        Behavior: null,
        DefaultFormValue: -1,
        DefaultValue: -1,
        ImeMode: null,
        OptionSetId: "74b145a3-7b19-e911-a844-000d3a309adf",
        OptionSetName: "msp_engagementmilestone_msp_nonrecurring",
        OptionSetType: 0,
        OptionSet: [
          {
            Color: "#0000ff",
            Label: "Yes",
            Value: 861980000,
            TransitionData: null,
          },
        ],
        ParentPicklistLogicalName: null,
        ChildPicklistLogicalNames: null,
        RequiredLevel: 0,
        SourceType: 0,
        SourceTypeMask: 0,
        CanBeSecuredForCreate: true,
        CanBeSecuredForRead: true,
        CanBeSecuredForUpdate: true,
      },
      _logicalName: "msp_nonrecurring",
      _displayName: "Non-Recurring?",
      _entityLogicalName: "msp_engagementmilestone",
      _optionSet: null,
      defaultFormValue: -1,
    },
    {
      _attributeType: null,
      attributeDescriptor: {
        Initialized: 2,
        LogicalName: "msp_milestonecategory",
        Id: {
          guid: "c18f28b0-c838-e911-a84e-000d3a309ec9",
        },
        EntityLogicalName: "msp_engagementmilestone",
        Type: "picklist",
        DisplayName: "Milestone Category",
        Description: "",
        IsGlobalFilterEnabled: false,
        IsSecured: false,
        IsSortableEnabled: false,
        IsValidForAdvancedFind: true,
        IsValidForCreate: true,
        IsValidForRead: true,
        IsValidForUpdate: true,
        IsRetrievable: false,
        IsCustomAttribute: true,
        ColumnNumber: 60,
        Behavior: null,
        DefaultFormValue: -1,
        DefaultValue: -1,
        ImeMode: null,
        OptionSetId: "d08f28b0-c838-e911-a84e-000d3a309ec9",
        OptionSetName: "msp_engagementmilestone_msp_milestonecategory",
        OptionSetType: 0,
        OptionSet: [
          {
            Color: "#0000ff",
            Label: "Deal Registration",
            Value: 861980003,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Dual Credit",
            Value: 861980004,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Post-Commit: MVP",
            Value: 861980001,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Pre-Commit: POC/Pilot/MVP",
            Value: 861980000,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Production",
            Value: 861980002,
            TransitionData: null,
          },
        ],
        ParentPicklistLogicalName: null,
        ChildPicklistLogicalNames: null,
        RequiredLevel: 2,
        SourceType: 0,
        SourceTypeMask: 0,
        CanBeSecuredForCreate: true,
        CanBeSecuredForRead: true,
        CanBeSecuredForUpdate: true,
      },
      _logicalName: "msp_milestonecategory",
      _displayName: "Milestone Category",
      _entityLogicalName: "msp_engagementmilestone",
      _optionSet: null,
      defaultFormValue: -1,
    },
    {
      _attributeType: null,
      attributeDescriptor: {
        Initialized: 2,
        LogicalName: "msp_milestonestatus",
        Id: {
          guid: "4243d929-cd38-e911-a84e-000d3a309ec9",
        },
        EntityLogicalName: "msp_engagementmilestone",
        Type: "picklist",
        DisplayName: "Milestone Status",
        Description: "",
        IsGlobalFilterEnabled: false,
        IsSecured: false,
        IsSortableEnabled: false,
        IsValidForAdvancedFind: true,
        IsValidForCreate: true,
        IsValidForRead: true,
        IsValidForUpdate: true,
        IsRetrievable: false,
        IsCustomAttribute: true,
        ColumnNumber: 62,
        Behavior: null,
        DefaultFormValue: 861980000,
        DefaultValue: 861980000,
        ImeMode: null,
        OptionSetId: "4b43d929-cd38-e911-a84e-000d3a309ec9",
        OptionSetName: "msp_engagementmilestone_msp_milestonestatus",
        OptionSetType: 0,
        OptionSet: [
          {
            Color: "#0000ff",
            Label: "Completed",
            Value: 861980003,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "On Track",
            Value: 861980000,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "At Risk",
            Value: 861980001,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Blocked",
            Value: 861980002,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Cancelled",
            Value: 861980004,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Lost to Competitor",
            Value: 861980005,
            TransitionData: null,
          },
        ],
        ParentPicklistLogicalName: null,
        ChildPicklistLogicalNames: null,
        RequiredLevel: 0,
        SourceType: 0,
        SourceTypeMask: 0,
        CanBeSecuredForCreate: true,
        CanBeSecuredForRead: true,
        CanBeSecuredForUpdate: true,
      },
      _logicalName: "msp_milestonestatus",
      _displayName: "Milestone Status",
      _entityLogicalName: "msp_engagementmilestone",
      _optionSet: null,
      defaultFormValue: 861980000,
    },
    {
      _attributeType: null,
      attributeDescriptor: {
        Initialized: 2,
        LogicalName: "msp_helpneeded",
        Id: {
          guid: "595b9378-d838-e911-a84e-000d3a309ec9",
        },
        EntityLogicalName: "msp_engagementmilestone",
        Type: "picklist",
        DisplayName: "Help Needed",
        Description: "",
        IsGlobalFilterEnabled: false,
        IsSecured: false,
        IsSortableEnabled: false,
        IsValidForAdvancedFind: true,
        IsValidForCreate: true,
        IsValidForRead: true,
        IsValidForUpdate: true,
        IsRetrievable: false,
        IsCustomAttribute: true,
        ColumnNumber: 64,
        Behavior: null,
        DefaultFormValue: -1,
        DefaultValue: -1,
        ImeMode: null,
        OptionSetId: "865b9378-d838-e911-a84e-000d3a309ec9",
        OptionSetName: "msp_engagementmilestone_msp_helpneeded",
        OptionSetType: 0,
        OptionSet: [
          {
            Color: "#0000ff",
            Label: "Azure Tech Skilling",
            Value: 861980014,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Billing, Licensing & Subscription",
            Value: 861980000,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Azure Capacity Availability",
            Value: 861980001,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Azure Service/Product Availability",
            Value: 100000000,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Discounting",
            Value: 861980002,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Exec Escalation",
            Value: 861980003,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Exec Sponsor (Engineering)",
            Value: 861980004,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Exec Sponsor (Non-Engineering)",
            Value: 861980005,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Exec Visit",
            Value: 861980006,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Funds [<100K]",
            Value: 861980007,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Funds [100K+]",
            Value: 861980008,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "No additional Corp. help needed",
            Value: 861980016,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Partner",
            Value: 861980009,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Resources [Engineering]",
            Value: 861980010,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Resources [Non-Engineering]",
            Value: 861980011,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "MS Services Support",
            Value: 861980015,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Technical Blockers",
            Value: 861980012,
            TransitionData: null,
          },
          {
            Color: "#0000ff",
            Label: "Technical Gaps",
            Value: 861980013,
            TransitionData: null,
          },
        ],
        ParentPicklistLogicalName: null,
        ChildPicklistLogicalNames: null,
        RequiredLevel: 0,
        SourceType: 0,
        SourceTypeMask: 0,
        CanBeSecuredForCreate: true,
        CanBeSecuredForRead: true,
        CanBeSecuredForUpdate: true,
      },
      _logicalName: "msp_helpneeded",
      _displayName: "Help Needed",
      _entityLogicalName: "msp_engagementmilestone",
      _optionSet: null,
      defaultFormValue: -1,
    },
  ];
};
export default GetSampleOptionSets;
