import iLookupFieldDefinition from "./iLookupFieldDefinition";
import iModalDailog from "./iModalDailog";
export default interface iColumnDefinition {
  name: string;
  readonly?: boolean;
  cellEdited?(cell: any, tmpGenericGrid: any): void;
  formatter?(cell: any, tmpGenericGrid: any): void;
  customEditor?(cell: any, tmpGenericGrid: any): void;
  tabulatorEditorUsed?: boolean;
  displayName?: string;
  toolTip?: string;
  isRequired?: boolean;
  isLinkColumn?: boolean;
  linkTo?: string;
  modalDailog?: iModalDailog;
  lookUpCol?: iLookupFieldDefinition;
  isHidden?: boolean;
  hygiene?: boolean;
  editCheck?(cell: any, tmpGenericGrid: any): boolean;
  headerFilter?: boolean;
  isFrozen?: boolean;
  width?: number;
  options?: any;
  autoGenerated?: boolean;
}
